import { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { Metadata } from "next";
import {SidebarProvider} from "@/components/providers/SidebarProvider";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <ClerkProvider>
      <SidebarProvider>
        <div className="h-full">{children}</div>
      </SidebarProvider>
      <SanityLive />
    </ClerkProvider>
  );
};
export default DashboardLayout;
