import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import DarkModeProvider from "@/components/providers/DarkModeProvider";


export const metadata: Metadata = {
  title: "Sonny LMS platform",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        <DarkModeProvider
          attribute="class"
          disableTransitionOnChange
          defaultTheme="dark"
        >
          {children}
        </DarkModeProvider>
      </body>
    </html>
  );
};
export default RootLayout;