import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Sonny LMS platform",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
export default RootLayout;