import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Sonny LMS platform",
  description: "Generated by create next app",
};

const  RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>) =>{
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
export default RootLayout;