import { ReactNode } from "react";

import { Metadata } from "next";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { getCourseById, getCourseProgress } from "@/sanity/lib/courses/queries";
import Sidebar from "@/components/dashboard/layout/Sidebar";
import { checkCourseAccess } from "@/lib/auth";

interface DashboardViewProps {
  children: ReactNode;
  params: Promise<{courseId:string}>;

}
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = async ({
  children,
  params,
}: DashboardViewProps) => {
  const user = await currentUser()
  const {courseId}  = await params;
  if (!user?.id) {
    return redirect('/')
  }
  const authResult = await checkCourseAccess(user?.id||null,courseId);
  if (!authResult.isAuthorized || !user?.id)  {
    return redirect(authResult.redirect!)
  }
  const [course, progress] = await Promise.all([
    getCourseById(courseId),
    getCourseProgress(user.id, courseId),
  ]);
  if (!course) {
    return redirect("/my-courses");
  }
  return (
    <div className="h-full">
      <Sidebar course={course} completedLessons={progress.completedLessons} />
      <div className="h-full lg:pt-[64px] pl-20 lg:pl-96">{children}</div>
    </div>
  );
};
export default DashboardLayout;
